### ISSUE TITLE
In game window is blank

### ISSUE THREAD

**Issue by nimrod46** [bloofi/CnC_TA#2]
Hi @bloofi, again...

seems like the script got broken or something in-game:
![image](https://user-images.githubusercontent.com/11810541/110974275-0abd9980-8367-11eb-9be9-35ace7027645.png)

**Comment by bloofi** [comment]
you have this error 100% of the time ? Did you try close/relaunch your browser ? Do you have multiples tabs opened with the game ?

**Comment by nimrod46** [comment]
@bloofi Hi! I just manage to fix the error when editing the script, the error lines number are wrong and I missed the source exception, the real one is: 
![image](https://user-images.githubusercontent.com/11810541/111008700-589fc500-839a-11eb-9208-862ada647626.png)


so the fix is to replace this ctor with any other existing ctor: 
`new qx.ui.layout.Dock();`
to
`new qx.ui.layout.Atom();`


I don't know which layout is the best, I don't really know anything about scripting this game, but the existing layouts that I have are:
![image](https://user-images.githubusercontent.com/11810541/111008881-c9df7800-839a-11eb-81d2-082d54753194.png)

**Comment by bloofi** [comment]
Yep, i think it's possible to achieve the same thing with others layouts.
Dunno why they removed this layout in particular :/ i've already noticed they'd remove some specific components from qooxdoo.
Must be since the last patch 21.1 few days ago.
I probably have shit tons of others scripts not working anymore because of this :(

Anyway, thanks for pointing this out, i'll push a fix soon for BI5

**Comment by nimrod46** [comment]
> Must be since the last patch 21.1 few days ago.

@bloofi Yeah I thought so.

It will be nice getting the fix fast as it will take some time to update the clients
Any way thanks!

**Comment by bloofi** [comment]
I made a quick fix with the qx.ui.layout.Atom, until i find a better solution.

https://github.com/bloofi/CnC_TA/blob/master/CnCTA-BaseInfoV5.user.js
